### ISSUE TITLE
Error build MSVC 2013

### ISSUE THREAD

**Issue by ghost** [dajoh/OpenSteamClient#4]
```
 1>OpenSteamClient_sd.lib(steammessages_clientserver.pb.obj) : error LNK2019: unresolved external symbol "public: int __thiscall google::protobuf::io::CodedInputStream::BytesUntilLimit(void)const " (?BytesUntilLimit@CodedInputStream@io@protobuf@google@@QBEHXZ) referenced in function "public: static bool __cdecl google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<unsigned int,7>(class google::protobuf::io::CodedInputStream *,class google::protobuf::RepeatedField<unsigned int> *)" (??$ReadPackedPrimitive@I$06@WireFormatLite@internal@protobuf@google@@SA_NPAVCodedInputStream@io@23@PAV?$RepeatedField@I@23@@Z)
```

**Comment by ghost** [comment]
what the hell?

**Comment by ghost** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/8020186/9270278/117d2a5e-4279-11e5-9e6a-e72e15d5b5a5.png)

**Comment by dajoh** [comment]
I recommend linking to the libraries in the ThirdParty folder, not your own. If you want to use your own however, you want to use lite version of libprotobuf. You will also need to generate the .pb.cpp files with your own protoc. You can see how this is done in GenerateProtobufs.bat.

**Comment by ghost** [comment]
i am generate all proto .cc.hh files

**Comment by ghost** [comment]
@dajoh Please show your library that you link
