### ISSUE TITLE
Trying build with default .lib

### ISSUE THREAD

**Issue by ghost** [dajoh/OpenSteamClient#5]
Recorded video: https://api.monosnap.com/rpc/file/download?id=F6XhK5HIFn0AJHRAElcPNAt3o5BRF3

**Comment by dajoh** [comment]
The .pb.cpp files aren't included in your OpenSteamClient project. If you can't get it to work, post the contents of both your project's vcxprojs, and the build log.

**Comment by ghost** [comment]
OK, I'll try and describe the results of

**Comment by ghost** [comment]
Right?

![screenshot_4](https://cloud.githubusercontent.com/assets/8020186/9289933/d2c3bc64-4387-11e5-8033-5df3cccaa19e.png)

**Comment by ghost** [comment]
Running with _SCL_SECURE_NO_WARNINGS

![screenshot_5](https://cloud.githubusercontent.com/assets/8020186/9290027/3cffac98-438b-11e5-85dd-2c1608fcd742.png)
