### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by Tenrys** [dajoh/OpenSteamClient#8]
I'm trying to build the example code, and it just doesn't work. Here is my setup:

![](http://tenrys.montoyo.net/ShareX/2015-08-30_14-14-37.png)

I'm using the libraries in the ThirdParty folder, and I built my own OpenSteamClient.

**Comment by Tenrys** [comment]
I'm having errors with cryptopp and libprotobuf-lite too. What the hell?
![](http://tenrys.montoyo.net/ShareX/2015-08-30_14-23-49.png)

**Comment by Tenrys** [comment]
Nevermind, it fixed itself, but now it's giving me this single error in Enums.hpp:

    	14	IntelliSense: enumeration value is out of 'int' range	c:\Users\tenry\Documents\Projects\MySteamBotPlusPlus\MySteamBotPlusPlus\OpenSteamClient\Enums.hpp	2305	34	MySteamBotPlusPlus

**Comment by ghost** [comment]
@Tenrys needed rebuild _crypto++_ and _protobuf_ to **msvc 2013**
